### ISSUE TITLE
NumberFeatures Tool sets output parameter to spurious output and does not refresh layer

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#607]
### Tasks to be done June 13 
- [ ]  Verify the fix

NumberFeatures Tool sets output parameter ("tempSortedPoints") to spurious output(tempSortedPoints) and does not refresh layer on the map. The output parameter passed to GP is incorrect if "Output Numbered Features" is not set

## Expected Behavior

The tool to set the output parameter correctly if "Output Numbered Features" is not set

## Current Behavior

The tool sets the output parameter to "tempSortedPoints" which doesn't refresh the layer on the map

## Possible Solution

1. Either have 2 tools with different outputs 
-or-
2. Have 2 output parameters: input (derived) and output

## Steps to Reproduce (for bugs)

1 Use the ClearingOperations template (so you have data, steps, etc)
2. Run the Clearing Operations "Collect and Number Structures" Task
3. At Number Structures step, when you run the NumberFeatures tool, do not enter a value for OutputNumbered Features
4. Run the tool, incorrect results:
    a. Output Numbered Features will now have: "..../tempSortedPoints" as a value
    b. The Input data set in "Features to Number" will not refresh on the map

## Your Environment

* Version used: Pro 2.0

![image](https://user-images.githubusercontent.com/3090809/30765514-0ec06868-9fbe-11e7-9645-6c87a8b22fea.png)

**Comment by csmoore** [comment]
Partial address in https://github.com/Esri/solutions-geoprocessing-toolbox/commit/0d381ba3cabe81faf31f49f454dd51a9de5fc9b8 

NOTE: Unfortunately I couldn't just set the output parameter to the input value during the tool run because that resulted in an error the next time the user used the tool/task (Pro keeps the previous values) - so this will likely need to be fully addressed in the tool parameters/design:

![image](https://user-images.githubusercontent.com/3090809/30766237-af2ab31e-9fc1-11e7-8ec5-7747a244a807.png)

**Comment by BobBooth** [comment]
I have updated to the latest Pro 2.1 and will test on it first.

**Comment by BobBooth** [comment]
Testing the tool in the Clearing Operations solution download here (http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=1875), I find that the tool has no default output name, which is good:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/678d92ff-6f84-4ae9-bd92-da270a79fcc9)
However, I am still seeing the numbered layer not having its number values displayed by the method indicated in the Task (Select layer in TOC, open Label section of ribbon, turn on labeling, set field, set lable position).
Zooming in and out did not trigger refresh. 
Finally, I opened the table for the layer and selected one of the features.
This caused the labels to appear.

tested with Pro 2.1.0 build 10257 
Windows 8.1 Enterprise

**Comment by BobBooth** [comment]
Also, strangely, when I go back in the task list (back button), Pro gets very slow/laggy, and when I add more points and try to re-run the tool I don't see an input feature set tool for sketching a polygon.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/ab91ef5b-d52c-426f-8a7d-d68b04621f17)

**Comment by BobBooth** [comment]
![ClearingOps_PendingEdits_warning.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/8c0d7da0-574e-41ab[Uploading... Finally_selecting_one_of_features_triggered_numbering.png ]-9501-e0410f316b13)![Number_labels_not_refereshed_by_actions_in_step.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/7be67a4f-5b5c-47ff-806f-80ef15058768)

**Comment by BobBooth** [comment]
![Finally_selecting_one_of_features_triggered_numbering.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/4d99c1d2-297b-4d99-8180-ca27f2d83292)

**Comment by kgonzago** [comment]
working with @BobBooth to understand issue

**Comment by kgonzago** [comment]
Using version Pro 2.1 (Final), @BobBooth was able to confirm, while I looked over his shoulder (via screenshare), this is no longer an issue. I would like another pair of eyes to confirm our findings. 

FYI @ACueva @dfoll @topowright

**Comment by kgonzago** [comment]
@ACueva, @BobBooth and I tested this issue thoroughly and determined it is no longer an issue in Pro 2.1.
